#xihua:
#校正中线
#闭环入库

set:
    video_save: true
    color: false
    motor_use: true
    zebra_detect: true
    cut_point_x: 0
    cut_point_y: 70
    cut_w: 640
    cut_h: 350
    ai_cut_x: 20
    ai_cut_y: 30
    ai_w: 600
    ai_h: 400

#    
main:
    garage_start: true
    #根据偏差[min_v_diff,max_v_diff]动态调整当前速度[min_v,max_v]，幂函数形式
    dy_speed_coef: 0
    dy_speed_exp: 0
    # max_v_diff应当尽量与turn_deviation_thresh相等
    max_v_diff: 40 #40
    min_v_diff: 5
    max_v: 26 #95
    min_v: 9 #95
    #根据偏差[min_v_diff,max_v_diff]动态调整当前速度[min_v,max_v]，Bezier曲线形式,p0在左上角，p1在右下角
    dy_speed_bezier_p0_ctrl_x: 37.47 #42.92 #18 # 25 #30.0 # [p0_x=start_error,p1_ctrl_x]
    dy_speed_bezier_p0_ctrl_y: 24.84 #20.73  #11 # 12 #12.0 # [p1_ctrl_y,p0_y=max_v] 
    dy_speed_bezier_p1_ctrl_x: 18.3 #22.74  #27 # 40 #40.0 # [p0_ctrl_x,p1_x=end_error]
    dy_speed_bezier_p1_ctrl_y: 13.6 #10.4 #17 # 12 #7.0 # [p1_y=min_v,p0_ctrl_y]
    
    slowdown_enhance_bezier_p0_ctrl_x: 142
    slowdown_enhance_bezier_p0_ctrl_y: 0.14
    slowdown_enhance_bezier_p1_ctrl_x: 31
    slowdown_enhance_bezier_p1_ctrl_y: 1.8

    slowdown_smooth_bezier_p0_ctrl_x: 142
    slowdown_smooth_bezier_p0_ctrl_y: 0.14
    slowdown_smooth_bezier_p1_ctrl_x: 31
    slowdown_smooth_bezier_p1_ctrl_y: 1.8
    slow_down_smooth_thresh: 5

    right_ray: -1.2
    left_ray: 1.0

    kp: 9 #1.6
    ki: 0
    kd: 20 #4.54
    dv: 0
    sc_kp: 1
    sc_ki: 0
    sc_kd: 0.5
    slow_down_kd: 0.2
    max_ag: 1133 ## 250
    min_ag: -1133 ## 0
    use_dv: false #false
    second_lap: false
    center_coef: 0

    #舵机动态kp kd，根据偏差deviation调整
    dy_kp_max: 27
    dy_kp_threshold: 20 #10 #62
    dy_kp_coef: 2.6
    dy_kp_exp: 2.8
    inc_dy_kp_threshold: 15 #30 #62
    inc_dy_kp_coef: 0.4
    inc_dy_kp_exp: 2
    dy_kd_threshold: 55 #62
    dy_kd_coef: 0

    #计算deviation时的重要参数：
    #-以IMGH-forward_dist作为分界线，上取up_scope个中心点，下取down_scope个中心点来衡量
    #--该值越大前瞻整体越远
    forward_dist: 40 #45 
    #--前瞻上下部分取点个数
    up_scope: 4 #4
    down_scope: 4 #4
    #--前瞻上下部分中心点对deviation的影响系数
    forward_coef1: 0.6
    forward_coef2: 0.4

    curvature_up_scope: 10
    curvature_down_scope: 8
    deviation_coef: 1
    slope_coef: 10
    slope_forward_dist_near: 40
    slope_forward_dist_far: 70
    slope_direction_forward_dist: 80
    ## 角度控制的前瞻位置
    #根据速度动态调整前瞻的参数，幂函数形式
    #-速度动态调整前瞻的阈值
    angle_enc_forward_threshold: 65 #120
    #-动态调整中线位置
    angle_enc_forward_dist_coef: 10 #0.0015
    angle_enc_forward_dist_exp: 1.7 #1
    angle_max_enc_forward_dist: 100
    angle_dy_forward_dist_kp: 1
    angle_dy_forward_dist_kd: 0.1
    #-动态调整上半部分像素点数量
    angle_enc_up_scope_coef: 0 #0.0015
    angle_enc_up_scope_exp: 1.884 #1
    angle_max_enc_up_scope: 12
    #-动态调整上半部分权重
    angle_enc_forward_coef1_coef: 0
    angle_enc_forward_coef1_exp: 1.5
    angle_max_enc_forward_coef1: 1.2

    ## 速度控制的前瞻位置
    #根据速度动态调整前瞻的参数，幂函数形式
    #-速度动态调整前瞻的阈值
    speed_enc_forward_threshold: 80 #120
    #-动态调整中线位置
    speed_dy_forward_dist_kp: 1
    speed_dy_forward_dist_kd: 0
    speed_enc_forward_dist_coef: 10 #0.0015
    speed_enc_forward_dist_exp: 1.8 #1
    speed_max_enc_forward_dist: 100
    speed_forward_dist: 50
    #-动态调整上半部分像素点数量
    speed_enc_up_scope_coef: 0 #0.0015
    speed_enc_up_scope_exp: 1.884 #1
    speed_max_enc_up_scope: 12
    #-动态调整上半部分权重
    speed_enc_forward_coef1_coef: 0
    speed_enc_forward_coef1_exp: 1.5
    speed_max_enc_forward_coef1: 1.2

    # 恒定速度与打角
    v_right_circle: [60,90] #[60,70]
    v_left_circle: [175,90] #[175,70]

    cone_speed: 5

turn:
    turn_deviation_thresh: 40
    turn_curvature_thresh: 0.15
    turn_slope_thresh: 0.7
    turn_out_slope_thresh : 0.55
    speed_ground: 6
    speed_ceiling: 16
    speed_in: 6
    motor_power: 25
    speed_ctrl_slope_coef: 15
    speed_ctrl_deviation_coef: 0.9
    angle_ctrl_slope_coef: 1
    angle_ctrl_deviation_coef: 1
    sc_kp: 0.9
    sc_ki: 0
    sc_kd: 5
    dy_speed_bezier_p0_ctrl_x: 24.3
    dy_speed_bezier_p0_ctrl_y: 9.9
    dy_speed_bezier_p1_ctrl_x: 44
    dy_speed_bezier_p1_ctrl_y: 10.9
    max_v_diff: 70 #40
    min_v_diff: 5
    slow_down_kd: 1.5
    slowdown_enhance_bezier_p0_ctrl_x: 201.5
    slowdown_enhance_bezier_p0_ctrl_y: 24.4
    slowdown_enhance_bezier_p1_ctrl_x: 165
    slowdown_enhance_bezier_p1_ctrl_y: 102.4

    slowdown_smooth_bezier_p0_ctrl_x: 201.5
    slowdown_smooth_bezier_p0_ctrl_y: 24.4
    slowdown_smooth_bezier_p1_ctrl_x: 165
    slowdown_smooth_bezier_p1_ctrl_y: 102.4
    slow_down_smooth_thresh: 5
right_circle:
    kp: 25 #8 #1.6
    ki: 0
    kd: 20 #20 #4.54
    dv: 0
    speed: 11
    circle_slow_down_kd: 0.5
    circle_dist: 50
    angle_forward_dist_kp: 1
    angle_forward_dist_kd: 0.4
    max_dy_forward_dist: 60
    min_dy_forward_dist: 30
    dy_forward_dist_coef_up: 10
    dy_forward_dist_exp_up: 1.7
    dy_forward_dist_coef_down: 0.08
    dy_forward_dist_exp_down: 0.8
    use: false 
    big_circle: false 
    count_start: 2
    in_find:
        kp: 9 #1.6
        ki: 0
        kd: 20 #4.54
        dv: 0
        ray_ag: 2
        speed: 13
    in_strai:
        kp: 12 #1.6
        ki: 0
        kd: 10 #4.54
        dv: 0
        ray_ag1: -0.94
        ray_ag2: -2.55 #-2.55
    in_circle:
        kp: 12 #1.6
        ki: 0
        kd: 15 #4.54
        dv: 0
        ray_ag1: 0.64 #0.84
        ray_ag2: -0.94
        ray_ag3: -2.45
        ray_ag4: -2.45
        ray_ag5: 0.44 #0.84
    inside_before:
        kp: 12
        ki: 0
        kd: 15 # 5.10
        dv: 0
        p: ['0','IMGH-5']
    inside:
        kp: 12 #1.6
        ki: 0
        kd: 20 #4.54
        dv: 0 #2
    out_find:
        kp: 13 #1.6
        ki: 0
        kd: 0 #4.54
        dv: 0 #2
        p:  ['2.7*IMGW/3','IMGH/3'] #['2*IMGW/3','IMGH/2'] #['2*IMGW/3','IMGH/2-5']
    out_strai: 
        find_pos: 15
        kp: 20 #1.6
        ki: 0
        kd: 20 #4.54
        dv: 0
    out:
        kp: 10 #1.6
        ki: 0
        kd: 10 #4.54
        ray_ag: 1.9
    out_out: 
        kp: 10 #1.6
        ki: 0
        kd: 0 #4.54
        dv: 0
#
left_circle:
    kp: 25 #8 #1.6
    ki: 0
    kd: 20 #20 #4.54
    dv: 0
    speed: 12
    circle_slow_down_kd: 2
    circle_dist: 42
    angle_forward_dist_kp: 1
    angle_forward_dist_kd: 0
    max_dy_forward_dist: 60
    min_dy_forward_dist: 35
    dy_forward_dist_coef_up: 20
    dy_forward_dist_exp_up: 1.7
    dy_forward_dist_coef_down: 40
    dy_forward_dist_exp_down: 1.3
    use: false 
    big_circle: false 
    count_start: 2
    in_find:
        kp: 0 #1.6
        ki: 0
        kd: 20 #4.54
        dv: 0
        ray_ag: 2
        speed: 13
    in_strai:
        kp: 12 #1.6
        ki: 0
        kd: 10 #4.54
        dv: 0
        ray_ag1: -0.94
        ray_ag2: -2.55 #-2.55
    in_circle:
        kp: 13 #1.6
        ki: 0
        kd: 15 #4.54
        dv: 0
        ray_ag1: 0.64 #0.84
        ray_ag2: -0.94
        ray_ag3: -2.45
        ray_ag4: -2.45
        ray_ag5: 0.44 #0.84
    inside_before:
        kp: 12
        ki: 0
        kd: 15 # 5.10
        dv: 0
        p: ['0','IMGH-5']
    inside:
        kp: 10 #1.6
        ki: 0
        kd: 20 #4.54
        dv: 0 #2
    out_find:
        kp: 15 #1.6
        ki: 0
        kd: 0 #4.54
        dv: 0 #2
        p:  ['2.7*IMGW/3','IMGH/3'] #['2*IMGW/3','IMGH/2'] #['2*IMGW/3','IMGH/2-5']
    out_strai: 
        find_pos: 15
        kp: 20 #1.6
        ki: 0
        kd: 20 #4.54
        dv: 0
    out:
        kp: 10 #1.6
        ki: 0
        kd: 10 #4.54
        ray_ag: 1.9
    out_out: 
        kp: 10 #1.6
        ki: 0
        kd: 0 #4.54
        dv: 0
#
repair:
    kp: 2
    ki: 0
    kd: 4
    dv: 0
    speed: -5
#
farm:
    kp: 1.3 #0.3 2.9高速80
    ki: 0
    kd: 2.6 #0.3 2低速50~70
    dv: 0
    speed: 14
    speed_out: 10
    dist: 35
    up_scope: 15
    down_scope: 25
    out_find_line: 35
    out_find_count: 30
    out_line: 30
    out_count: 70
#
hump:
    kp: 2
    ki: 0
    kd: 4
    dv: 0
    speed: 110
    mend_up_line: 50
    on_line: 25
#
start:
    kp: 2
    ki: 0
    kd: 4
    dv: 0
    left: false
    start_dist: 4
    x_thresh: 24
    v_left: [ 200, 75 ]
    v_right: [ 40, 75 ]
    start_speed: 10
    start_angle: 0
#
end:
    kp: 2
    ki: 0
    kd: 4
    dv: 0
    end_dist: 55
    end_whitecount: 20
    v_left_garage: [220,50]
    v_right_garage: [5,50]
    end_speed: 10
    end_angle: 0
#
zebra:
    kp: 2
    ki: 0
    kd: 4
    dv: 0
    zebra_far_dist: 60 #50 # 最好大于巡线门槛
    zebra_near_dist: 40 # 小于上一值  30
    v_left_zebra: [125,50]
    v_right_zebra: [125,50]
#
hill:
    kp: 2 #2
    ki: 0
    kd: 4
    dv: 0
    speed: 120
    mid_bot_y: 5
    mid_top_y: 50
    frame: 26
