use_python_inference: false
mode: fluid
draw_threshold: 0.5
metric: VOC
arch: SSD
min_subgraph_size: 3
with_background: true
Preprocess:
- image_shape:
  - 224
  - 224
  interp: 1
  max_size: 0
  resize_box: false
  target_size: 224
  type: Resize
  use_cv2: true
- channel_first: true
  to_bgr: true
  type: Permute
- is_channel_first: true
  is_scale: false
  mean:
  - 127.5
  - 127.5
  - 127.5
  std:
  - 127.502231
  - 127.502231
  - 127.502231
  type: Normalize
label_list:
- background
- bridge
- tractor
- corn
- pig
- bump
